name: publish-yc-container

on:
  workflow_dispatch:
    inputs:
      iam:
        required: true
        type: string
        description: 'User or service account IAM token.'
      registry:
        required: true
        type: string
        description: 'yc container registry id.'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: iam
          password: ${{ github.event.inputs.iam }}
          registry: cr.yandex

      - name: build push
        uses: docker/build-push-action@v3
        with:
          tags: cr.yandex/${{ github.event.inputs.registry }}/${{ GITHUB_REPOSITORY }}:${{ GITHUB_SHA }}
          push: true
          context: .
